// WebAudio sink for the emulator. Samples are generated by the core at 44.1kHz
// and pushed each frame; we queue them as small AudioBuffers scheduled
// back-to-back so playback stays gapless without a ScriptProcessor/Worklet.
const SAMPLE_RATE = 44100;

export class NesAudio {
  private ctx: AudioContext | null = null;
  private gain: GainNode | null = null;
  private next = 0; // scheduled end time of the last queued buffer

  /** Create/resume the context. Must be called from a user gesture. */
  resume(): void {
    if (!this.ctx) {
      const Ctor =
        window.AudioContext ||
        (window as unknown as { webkitAudioContext: typeof AudioContext })
          .webkitAudioContext;
      if (!Ctor) return;
      this.ctx = new Ctor();
      this.gain = this.ctx.createGain();
      this.gain.gain.value = 0.5;
      this.gain.connect(this.ctx.destination);
      this.next = 0;
    }
    void this.ctx.resume();
  }

  /** Queue one frame's worth of mono samples for playback. */
  pump(samples: Float32Array): void {
    const ctx = this.ctx;
    if (!ctx || !this.gain || samples.length === 0) return;
    // The core targets 44.1kHz; WebAudio resamples to the device rate.
    const buf = ctx.createBuffer(1, samples.length, SAMPLE_RATE);
    // set() takes ArrayLike<number>, sidestepping Float32Array buffer-generic variance.
    buf.getChannelData(0).set(samples);
    const src = ctx.createBufferSource();
    src.buffer = buf;
    src.connect(this.gain);
    const now = ctx.currentTime;
    // Resync if we have fallen behind (or on first push), keeping a small lead.
    if (this.next < now + 0.02) this.next = now + 0.08;
    src.start(this.next);
    this.next += samples.length / SAMPLE_RATE;
  }

  suspend(): void {
    void this.ctx?.suspend();
  }

  close(): void {
    void this.ctx?.close();
    this.ctx = null;
    this.gain = null;
  }
}
