x-build-base: &build-base
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app
  restart: "no"

x-web-base: &web-base
  image: python:3-alpine
  volumes:
    - ./web:/app/web
  working_dir: /app
  command: python -m http.server 5173 --directory /app/web

services:
  # Development services
  dev:
    <<: *build-base
    profiles: [dev]
    command: build_all.sh

  test:
    <<: *build-base
    profiles: [dev, test]
    command: build_and_test.sh

  shell:
    <<: *build-base
    profiles: [dev]
    command: /bin/bash
    tty: true
    stdin_open: true

  # Web server for development
  web-dev:
    <<: *web-base
    profiles: [dev]
    restart: "no"
    ports:
      - "5173:5173"
